# Generated by Django 4.2.4 on 2024-03-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estados',
            new_name='estado',
        ),
    ]
