# Generated by Django 4.2.4 on 2023-10-03 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('RUC', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=50, null=True)),
                ('num_telefono', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cuenta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('saldo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_factura', models.CharField(max_length=50)),
                ('total_venta', models.IntegerField()),
                ('impuesto_total', models.IntegerField()),
                ('descuento_total', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.clientes')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.estados')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_producto', models.CharField(max_length=50)),
                ('precio_costo', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('cod_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.categoria')),
                ('cod_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.marca')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('credit', 'Credito'), ('cont', 'Contado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('descripcion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cantidad_saliente', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.producto')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('razon_social', models.CharField(max_length=100)),
                ('RUC', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=50, null=True)),
                ('num_telefono', models.CharField(max_length=12, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.estados')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.estados'),
        ),
        migrations.CreateModel(
            name='libro_mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('num_asiento', models.IntegerField()),
                ('concepto', models.CharField(max_length=200)),
                ('debe', models.IntegerField()),
                ('haber', models.IntegerField()),
                ('saldo', models.IntegerField()),
                ('num_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='libro_diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('num_asiento', models.IntegerField()),
                ('concepto', models.CharField(max_length=200)),
                ('debe', models.IntegerField()),
                ('haber', models.IntegerField()),
                ('num_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('entrada', models.IntegerField()),
                ('salida', models.IntegerField()),
                ('existencia', models.IntegerField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.producto')),
            ],
        ),
        migrations.CreateModel(
            name='factura_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.IntegerField()),
                ('impuesto', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('total_precio', models.IntegerField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.producto')),
                ('num_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='metodo_de_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.metodo_pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.tipo_factura'),
        ),
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cantidad_entrante', models.IntegerField()),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.producto')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.estados'),
        ),
    ]
