# Generated by Django 4.2.4 on 2023-11-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField(null=True)),
                ('total_precio', models.IntegerField()),
                ('impuesto', models.IntegerField(null=True)),
                ('descuento', models.IntegerField(null=True)),
                ('cod_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.producto')),
                ('num_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.factura')),
            ],
        ),
    ]
