# Generated by Django 4.2.4 on 2023-10-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='cantidad_entrante',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='descripcion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='descuento_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='impuesto_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_venta',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='impuesto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='factura_detalle',
            name='precio_unitario',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='existencia',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cantidad_saliente',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='cod_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor.producto'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='descripcion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha_salida',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='total_venta',
            field=models.IntegerField(null=True),
        ),
    ]
