# Generated by Django 4.2.4 on 2023-10-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva_producto',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
