# Generated by Django 4.2.4 on 2023-09-03 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_entrada_cantidad_entrante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_detalle',
            name='num_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.factura'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.IntegerField(),
        ),
    ]
