# Generated by Django 4.2.4 on 2023-11-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_inventario_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='referencia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
