# Generated by Django 4.2.4 on 2023-10-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_producto_iva_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='iva_producto',
        ),
    ]
