# Generated by Django 4.2.4 on 2023-08-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_entrada_cantidad_entrante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_detalle',
            name='total_precio',
            field=models.IntegerField(),
        ),
    ]
