# Generated by Django 4.2.4 on 2023-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_factura_detalle_total_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida',
            field=models.CharField(),
        ),
    ]
