# Generated by Django 4.2.4 on 2023-11-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_alter_inventario_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
