# Generated by Django 4.2.4 on 2023-09-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_remove_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='medida',
        ),
    ]
