# Generated by Django 4.2.4 on 2023-09-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_remove_producto_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='medida',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
