# Generated by Django 4.2.4 on 2023-09-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_remove_producto_descuento_remove_producto_medida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='num_factura',
            field=models.IntegerField(),
        ),
    ]
