# Generated by Django 4.2.4 on 2023-09-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_remove_producto_descuento_remove_producto_medida'),
        ('gestor', '0008_cuenta_libro_mayor_libro_diario'),
    ]

    operations = [
    ]
